// Canonical fundamentals shapes used by unit tests. Tuned to produce
// predictable scoring outcomes so tests remain deterministic.
// Shape mirrors Fundamentals in lib/yahoo.ts exactly.

import type { Fundamentals } from "../yahoo";

// A strong, healthy, wide-moat company
export const strongCompany: Fundamentals = {
  symbol: "STRONG",
  sector: "Technology",
  industry: "Software",
  longBusinessSummary: "A strong hypothetical software company.",
  revenueGrowth: 0.18,
  earningsGrowth: 0.22,
  operatingMargin: 0.35,
  profitMargin: 0.28,
  roe: 0.32,
  roa: 0.18,
  debtToEquity: 25,              // low leverage (Yahoo returns % here)
  totalCash: 50_000_000_000,
  totalDebt: 10_000_000_000,
  currentRatio: 2.1,
  quickRatio: 1.9,
  peTrailing: 28,
  peForward: 24,
  priceToBook: 10,
  priceToSales: 8,
  peg: 0.9,
  evToEbitda: 18,
  beta: 1.1,
  marketCap: 1_100_000_000_000,
  enterpriseValue: 1_200_000_000_000,
  freeCashflow: 80_000_000_000,
  operatingCashflow: 95_000_000_000,
  dividendYield: 0.005,
  payoutRatio: 0.15,
  targetMeanPrice: 450,
  recommendationKey: "buy",
  numberOfAnalystOpinions: 45,
  totalRevenue: 250_000_000_000,
  revenuePerShare: 90,
  currency: "USD",
  asOf: "2026-04-21T00:00:00Z",
};

// A weak / distressed company
export const distressedCompany: Fundamentals = {
  symbol: "WEAK",
  sector: "Industrials",
  industry: "Airlines",
  longBusinessSummary: "A struggling hypothetical airline.",
  revenueGrowth: -0.05,
  earningsGrowth: -0.40,
  operatingMargin: -0.05,
  profitMargin: -0.08,
  roe: -0.12,
  roa: -0.05,
  debtToEquity: 450,             // very high leverage
  totalCash: 500_000_000,
  totalDebt: 15_000_000_000,
  currentRatio: 0.7,             // below 1 — liquidity strain
  quickRatio: 0.5,
  peTrailing: null,              // often null when losing money
  peForward: 25,
  priceToBook: 0.5,
  priceToSales: 0.2,
  peg: null,
  evToEbitda: 35,
  beta: 1.8,
  marketCap: 3_500_000_000,
  enterpriseValue: 18_000_000_000,
  freeCashflow: -2_000_000_000,  // negative FCF
  operatingCashflow: -500_000_000,
  dividendYield: 0,
  payoutRatio: 0,
  targetMeanPrice: 18,
  recommendationKey: "hold",
  numberOfAnalystOpinions: 12,
  totalRevenue: 20_000_000_000,
  revenuePerShare: 280,
  currency: "USD",
  asOf: "2026-04-21T00:00:00Z",
};

// A missing-data case (sparse fundamentals; many nulls)
export const sparseCompany: Fundamentals = {
  symbol: "SPARSE",
  sector: "Real Estate",
  industry: "REIT - Residential",
  longBusinessSummary: null,
  revenueGrowth: null,
  earningsGrowth: null,
  operatingMargin: null,
  profitMargin: null,
  roe: null,
  roa: null,
  debtToEquity: null,
  totalCash: null,
  totalDebt: null,
  currentRatio: null,
  quickRatio: null,
  peTrailing: 18,
  peForward: null,
  priceToBook: null,
  priceToSales: null,
  peg: null,
  evToEbitda: null,
  beta: null,
  marketCap: 5_000_000_000,
  enterpriseValue: null,
  freeCashflow: null,
  operatingCashflow: null,
  dividendYield: null,
  payoutRatio: null,
  targetMeanPrice: null,
  recommendationKey: null,
  numberOfAnalystOpinions: null,
  totalRevenue: null,
  revenuePerShare: null,
  currency: "USD",
  asOf: "2026-04-21T00:00:00Z",
};
