-- Expand India coverage to ~75 additional Nifty 100 / Nifty Next 50 names
insert into stocks (market, symbol, name, industry, featured) values
  ('NSE','SBIN','State Bank of India','Public Banking',false),
  ('NSE','KOTAKBANK','Kotak Mahindra Bank','Private Banking',false),
  ('NSE','BAJFINANCE','Bajaj Finance','NBFC',false),
  ('NSE','BAJAJFINSV','Bajaj Finserv','Financial Services',false),
  ('NSE','HCLTECH','HCL Technologies','IT Services',false),
  ('NSE','WIPRO','Wipro','IT Services',false),
  ('NSE','TECHM','Tech Mahindra','IT Services',false),
  ('NSE','ULTRACEMCO','UltraTech Cement','Cement',false),
  ('NSE','NESTLEIND','Nestle India','Consumer / FMCG',false),
  ('NSE','DIVISLAB','Divi''s Laboratories','Pharma',false),
  ('NSE','DRREDDY','Dr. Reddy''s Laboratories','Pharma',false),
  ('NSE','CIPLA','Cipla','Pharma',false),
  ('NSE','APOLLOHOSP','Apollo Hospitals','Healthcare',false),
  ('NSE','ADANIENT','Adani Enterprises','Conglomerate',false),
  ('NSE','ADANIPORTS','Adani Ports','Ports & Logistics',false),
  ('NSE','POWERGRID','Power Grid Corp','Utilities',false),
  ('NSE','NTPC','NTPC','Utilities',false),
  ('NSE','ONGC','Oil & Natural Gas Corp','Oil & Gas',false),
  ('NSE','COALINDIA','Coal India','Mining',false),
  ('NSE','TATAMOTORS','Tata Motors','Auto',false),
  ('NSE','M&M','Mahindra & Mahindra','Auto',false),
  ('NSE','BAJAJ-AUTO','Bajaj Auto','Auto',false),
  ('NSE','EICHERMOT','Eicher Motors','Auto',false),
  ('NSE','HEROMOTOCO','Hero MotoCorp','Auto',false),
  ('NSE','TVSMOTOR','TVS Motor','Auto',false),
  ('NSE','TATASTEEL','Tata Steel','Steel',false),
  ('NSE','JSWSTEEL','JSW Steel','Steel',false),
  ('NSE','HINDALCO','Hindalco','Metals',false),
  ('NSE','VEDL','Vedanta','Mining',false),
  ('NSE','GRASIM','Grasim Industries','Cement',false),
  ('NSE','SHRIRAMFIN','Shriram Finance','NBFC',false),
  ('NSE','SBILIFE','SBI Life Insurance','Insurance',false),
  ('NSE','HDFCLIFE','HDFC Life Insurance','Insurance',false),
  ('NSE','ICICIGI','ICICI Lombard','Insurance',false),
  ('NSE','INDUSINDBK','IndusInd Bank','Private Banking',false),
  ('NSE','BRITANNIA','Britannia Industries','Consumer / FMCG',false),
  ('NSE','DABUR','Dabur India','Consumer / FMCG',false),
  ('NSE','GODREJCP','Godrej Consumer','Consumer / FMCG',false),
  ('NSE','MARICO','Marico','Consumer / FMCG',false),
  ('NSE','COLPAL','Colgate-Palmolive India','Consumer / FMCG',false),
  ('NSE','DMART','Avenue Supermarts','Retail',false),
  ('NSE','TRENT','Trent','Retail',false),
  ('NSE','ZOMATO','Zomato','Food Delivery',false),
  ('NSE','NAUKRI','Info Edge','Internet',false),
  ('NSE','PAYTM','One 97 Communications','Fintech',false),
  ('NSE','NYKAA','FSN E-Commerce','E-commerce',false),
  ('NSE','POLICYBZR','PB Fintech','Fintech',false),
  ('NSE','LTIM','LTIMindtree','IT Services',false),
  ('NSE','MPHASIS','Mphasis','IT Services',false),
  ('NSE','PERSISTENT','Persistent Systems','IT Services',false),
  ('NSE','COFORGE','Coforge','IT Services',false),
  ('NSE','TATAELXSI','Tata Elxsi','IT Services',false),
  ('NSE','TATACONSUM','Tata Consumer','Consumer / FMCG',false),
  ('NSE','SIEMENS','Siemens India','Capital Goods',false),
  ('NSE','ABB','ABB India','Capital Goods',false),
  ('NSE','HAVELLS','Havells India','Electricals',false),
  ('NSE','VOLTAS','Voltas','Consumer Durables',false),
  ('NSE','BOSCHLTD','Bosch','Auto Ancillary',false),
  ('NSE','MOTHERSON','Samvardhana Motherson','Auto Ancillary',false),
  ('NSE','BHARATFORG','Bharat Forge','Engineering',false),
  ('NSE','CUMMINSIND','Cummins India','Engineering',false),
  ('NSE','LUPIN','Lupin','Pharma',false),
  ('NSE','BIOCON','Biocon','Pharma',false),
  ('NSE','ZYDUSLIFE','Zydus Lifesciences','Pharma',false),
  ('NSE','TORNTPHARM','Torrent Pharmaceuticals','Pharma',false),
  ('NSE','GLAXO','GlaxoSmithKline Pharmaceuticals','Pharma',false),
  ('NSE','PFIZER','Pfizer India','Pharma',false),
  ('NSE','IRCTC','Indian Railway Catering','Travel',false),
  ('NSE','INDIGO','InterGlobe Aviation','Aviation',false),
  ('NSE','BEL','Bharat Electronics','Defense',false),
  ('NSE','HAL','Hindustan Aeronautics','Defense',false),
  ('NSE','PIIND','PI Industries','Agrochemicals',false),
  ('NSE','UPL','UPL Ltd','Agrochemicals',false),
  ('NSE','GAIL','GAIL India','Oil & Gas',false),
  ('NSE','IOC','Indian Oil Corporation','Oil & Gas',false),
  ('NSE','BPCL','Bharat Petroleum','Oil & Gas',false),
  ('NSE','AMBUJACEM','Ambuja Cements','Cement',false),
  ('NSE','SHREECEM','Shree Cement','Cement',false),
  ('NSE','ACC','ACC Ltd','Cement',false)
on conflict (market, symbol) do update set featured = excluded.featured, industry = excluded.industry;

-- Expand US coverage (S&P 100-ish)
insert into stocks (market, symbol, name, industry, featured) values
  ('NASDAQ','NFLX','Netflix','Streaming',false),
  ('NASDAQ','AMD','Advanced Micro Devices','Semiconductors',false),
  ('NASDAQ','INTC','Intel','Semiconductors',false),
  ('NASDAQ','QCOM','Qualcomm','Semiconductors',false),
  ('NASDAQ','CSCO','Cisco Systems','Networking',false),
  ('NASDAQ','ADBE','Adobe','Software',false),
  ('NASDAQ','CRM','Salesforce','Software',false),
  ('NASDAQ','ORCL','Oracle','Software',false),
  ('NASDAQ','PYPL','PayPal','Payments',false),
  ('NASDAQ','INTU','Intuit','Software',false),
  ('NASDAQ','TXN','Texas Instruments','Semiconductors',false),
  ('NASDAQ','AMAT','Applied Materials','Semiconductors',false),
  ('NASDAQ','LRCX','Lam Research','Semiconductors',false),
  ('NASDAQ','COST','Costco','Retail',false),
  ('NASDAQ','SBUX','Starbucks','Restaurants',false),
  ('NASDAQ','ABNB','Airbnb','Travel',false),
  ('NASDAQ','UBER','Uber Technologies','Ride Share',false),
  ('NASDAQ','LYFT','Lyft','Ride Share',false),
  ('NASDAQ','BKNG','Booking Holdings','Travel',false),
  ('NYSE','MA','Mastercard','Payments',false),
  ('NYSE','BAC','Bank of America','Banking',false),
  ('NYSE','WFC','Wells Fargo','Banking',false),
  ('NYSE','GS','Goldman Sachs','Investment Banking',false),
  ('NYSE','MS','Morgan Stanley','Investment Banking',false),
  ('NYSE','C','Citigroup','Banking',false),
  ('NYSE','AXP','American Express','Payments',false),
  ('NYSE','DIS','Walt Disney','Entertainment',false),
  ('NYSE','NKE','Nike','Apparel',false),
  ('NYSE','HD','Home Depot','Retail',false),
  ('NYSE','LOW','Lowe''s','Retail',false),
  ('NYSE','MCD','McDonald''s','Restaurants',false),
  ('NYSE','KO','Coca-Cola','Beverages',false),
  ('NYSE','PEP','PepsiCo','Beverages',false),
  ('NYSE','PG','Procter & Gamble','Consumer Products',false),
  ('NYSE','CVS','CVS Health','Pharmacy',false),
  ('NYSE','PFE','Pfizer','Pharma',false),
  ('NYSE','MRK','Merck','Pharma',false),
  ('NYSE','LLY','Eli Lilly','Pharma',false),
  ('NYSE','ABBV','AbbVie','Pharma',false),
  ('NYSE','ABT','Abbott Laboratories','Healthcare',false),
  ('NYSE','TMO','Thermo Fisher Scientific','Life Sciences',false),
  ('NYSE','XOM','Exxon Mobil','Oil & Gas',false),
  ('NYSE','CVX','Chevron','Oil & Gas',false),
  ('NYSE','BA','Boeing','Aerospace',false),
  ('NYSE','CAT','Caterpillar','Heavy Equipment',false),
  ('NYSE','GE','General Electric','Industrial',false),
  ('NYSE','HON','Honeywell','Industrial',false),
  ('NYSE','UPS','United Parcel Service','Logistics',false),
  ('NYSE','FDX','FedEx','Logistics',false),
  ('NYSE','F','Ford Motor','Auto',false),
  ('NYSE','GM','General Motors','Auto',false),
  ('NYSE','T','AT&T','Telecom',false),
  ('NYSE','VZ','Verizon','Telecom',false),
  ('NYSE','TGT','Target','Retail',false),
  ('NYSE','SHOP','Shopify','E-commerce',false),
  ('NYSE','PLTR','Palantir','Software',false),
  ('NYSE','SPOT','Spotify','Streaming',false)
on conflict (market, symbol) do update set industry = excluded.industry;
